<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class RiwayatTransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $riwayat_transaksis = [
            [
                'id_riwayat_transaksi' => 1,
                'id_transaksi' => 1,
                'id_akun' => 2,
                'id_perorangan' => 1,
                'tanggal_transaksi' => '2023-01-01',
                'total_transaksi' => 325000,
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => '2023-01-31',
                'tanggal_selesai' => '2023-01-15',
                'status_akhir' => 'success',
                'total_pembayaran' => 325000,
                'denda' => 0,
                'durasi_peminjaman' => 14,
                'keterangan' => 'Peminjaman oksigen+nitrogen lunas (dikembalikan)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 2,
                'id_transaksi' => 4,
                'id_akun' => 5,
                'id_perorangan' => 4,
                'tanggal_transaksi' => '2023-01-04',
                'total_transaksi' => 150000,
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => '2023-02-03',
                'tanggal_selesai' => '2023-01-19',
                'status_akhir' => 'success',
                'total_pembayaran' => 150000,
                'denda' => 0,
                'durasi_peminjaman' => 15,
                'keterangan' => 'Peminjaman oksigen lunas (dikembalikan)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 3,
                'id_transaksi' => 5,
                'id_akun' => 6,
                'id_perorangan' => 5,
                'tanggal_transaksi' => '2023-01-05',
                'total_transaksi' => 150000,
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => '2023-02-04',
                'tangaal_selesai' => '2023-01-20',
                'status_akhir' => 'success',
                'total_pembayaran' => 150000,
                'denda' => 50000,
                'durasi_peminjaman' => 15,
                'keterangan' => 'Peminjaman oksigen lunas (tabung rusak)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 4,
                'id_transaksi' => 6,
                'id_akun' => 7,
                'id_perorangan' => 6,
                'tanggal_transaksi' => '2023-01-06',
                'total_transaksi' => 150000,
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => null,
                'tanggal_selesai' => '2023-01-06',
                'status_akhir' => 'success',
                'total_pembayaran' => 150000,
                'denda' => 0,
                'durasi_peminjaman' => null,
                'keterangan' => 'Isi ulang oksigen lunas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 5,
                'id_transaksi' => 7,
                'id_akun' => 8,
                'id_perorangan' => 7,
                'tanggal_transaksi' => '2023-01-07',
                'total_transaksi' => 375000,
                'jumlah_dibayar' => 375000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => '2023-02-06',
                'tanggal_selesai' => '2023-01-22',
                'status_akhir' => 'success',
                'total_pembayaran' => 375000,
                'denda' => 0,
                'durasi_peminjaman' => 15,
                'keterangan' => 'Peminjaman oksigen + isi ulang argon+aceteline (dikembalikan)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 6,
                'id_transaksi' => 8,
                'id_akun' => 9,
                'id_perorangan' => 8,
                'tanggal_transaksi' => '2023-01-08',
                'total_transaksi' => 225000,
                'jumlah_dibayar' => 225000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => '2023-02-07',
                'tanggal_selesai' => '2023-01-23',
                'status_akhir' => 'success',
                'total_pembayaran' => 225000,
                'denda' => 0,
                'durasi_peminjaman' => 15,
                'keterangan' => 'Peminjaman aceteline + isi ulang argon (dikembalikan)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 7,
                'id_transaksi' => 9,
                'id_akun' => 10,
                'id_perorangan' => 9,
                'tanggal_transaksi' => '2023-01-09',
                'total_transaksi' => 225000,
                'jumlah_dibayar' => 225000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => '2023-02-08',
                'tanggal_selesai' => '2023-01-25',
                'status_akhir' => 'success',
                'total_pembayaran' => 225000,
                'denda' => 70000,
                'durasi_peminjaman' => 16,
                'keterangan' => 'Peminjaman aceteline (dikembalikan terlambat)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 8,
                'id_transaksi' => 11,
                'id_akun' => 12,
                'id_perorangan' => 11,
                'tanggal_transaksi' => '2023-01-11',
                'total_transaksi' => 325000,
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => null,
                'tanggal_selesai' => '2023-01-11',
                'status_akhir' => 'success',
                'total_pembayaran' => 325000,
                'denda' => 35000,
                'durasi_peminjaman' => null,
                'keterangan' => 'Isi ulang aceteline+nitrogen lunas (+denda)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 9,
                'id_transaksi' => 16,
                'id_akun' => null,
                'id_perorangan' => 16,
                'tanggal_transaksi' => '2024-01-15',
                'total_transaksi' => 325000,
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => null,
                'tanggal_selesai' => '2024-02-02',
                'status_akhir' => 'success',
                'total_pembayaran' => 325000,
                'denda' => 0,
                'durasi_peminjaman' => 17,
                'keterangan' => 'Peminjaman Oksigen, Nitrogen Kode O001 dan NO001 (lunas)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 10,
                'id_transaksi' => 20,
                'id_akun' => null,
                'id_perorangan' => 20,
                'tanggal_transaksi' => '2024-01-15',
                'total_transaksi' => 150000,
                'jumlah_dibayar' => 245000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => '2004-02-15',
                'tanggal_selesai' => '2024-02-18',
                'status_akhir' => 'success',
                'total_pembayaran' => 150000,
                'denda' => 70000,
                'durasi_peminjaman' => 33,
                'keterangan' => 'Peminjaman Oksigen (denda keterlambatan dibayar lunas)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 11,
                'id_transaksi' => 21,
                'id_akun' => null,
                'id_perorangan' => 21,
                'tanggal_transaksi' => '2024-01-15',
                'total_transaksi' => 150000,
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => null,
                'tanggal_selesai' => '2024-01-15',
                'status_akhir' => 'success',
                'total_pembayaran' => 150000,
                'denda' => 0,
                'durasi_peminjaman' => null,
                'keterangan' => 'Perorangan Isi Ulang Oksigen Lunas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 12,
                'id_transaksi' => 22,
                'id_akun' => null,
                'id_perorangan' => 22,
                'tanggal_transaksi' => '2025-01-15',
                'total_transaksi' => 725000,
                'jumlah_dibayar' => 725000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => null,
                'tanggal_selesai' => '2024-01-30',
                'status_akhir' => 'success',
                'total_pembayaran' => 725000,
                'denda' => 0,
                'durasi_peminjaman' => 15,
                'keterangan' => 'Perorangan Isi ulang dan Peminjaman (Selesai)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 13,
                'id_transaksi' => 26,
                'id_akun' => null,
                'id_perorangan' => 26,
                'tanggal_transaksi' => '2025-01-15',
                'total_transaksi' => 325000,
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'transfer',
                'tanggal_jatuh_tempo' => null,
                'tanggal_selesai' => '2024-01-15',
                'status_akhir' => 'success',
                'total_pembayaran' => 325000,
                'denda' => 0,
                'durasi_peminjaman' => null,
                'keterangan' => 'Perorangan Isi Ulang Oksegen dan Nitrogen (Lunas)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 14,
                'id_transaksi' => 27,
                'id_akun' => null,
                'id_perorangan' => 27,
                'tanggal_transaksi' => '2025-01-15',
                'total_transaksi' => 1000000,
                'jumlah_dibayar' => 500000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => '2004-02-15',
                'tanggal_selesai' => '2024-02-20',
                'status_akhir' => 'success',
                'total_pembayaran' => 1000000,
                'denda' => 70000,
                'durasi_peminjaman' => 35,
                'keterangan' => 'Perorangan isi ulang+pinjam pengembalian terlambat + denda (lunas)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_riwayat_transaksi' => 15,
                'id_transaksi' => 29,
                'id_akun' => null,
                'id_perorangan' => 29,
                'tanggal_transaksi' => '2025-01-15',
                'total_transaksi' => 1000000,
                'jumlah_dibayar' => 250000,
                'metode_pembayaran' => 'tunai',
                'tanggal_jatuh_tempo' => '2004-02-15',
                'tanggal_selesai' => '2004-02-25',
                'status_akhir' => 'success',
                'total_pembayaran' => 1000000,
                'denda' => 70000,
                'durasi_peminjaman' => 40,
                'keterangan' => 'Perorangan isi ulang+pinjam pengembalian terlambat + denda (lunas)',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('riwayat_transaksis')->insert($riwayat_transaksis);
    }
}
