<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class TransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transaksis = [
            [
                'id_transaksi' => 1,
                'id_akun' => 1,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-01',
                'waktu_transaksi' => '08:00:00',
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-05-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 2,
                'id_akun' => 2,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-02',
                'waktu_transaksi' => '09:30:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 3,
                'id_akun' => 3,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-03',
                'waktu_transaksi' => '10:15:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 4,
                'id_akun' => 4,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-04',
                'waktu_transaksi' => '11:00:00',
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-03',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 5,
                'id_akun' => 5,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-05',
                'waktu_transaksi' => '13:45:00',
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-04',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 6,
                'id_akun' => 6,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-06',
                'waktu_transaksi' => '14:30:00',
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 7,
                'id_akun' => 7,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-07',
                'waktu_transaksi' => '15:00:00',
                'jumlah_dibayar' => 375000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-06',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 8,
                'id_akun' => 8,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-08',
                'waktu_transaksi' => '16:15:00',
                'jumlah_dibayar' => 225000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-07',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 9,
                'id_akun' => 9,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-09',
                'waktu_transaksi' => '09:00:00',
                'jumlah_dibayar' => 225000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 10,
                'id_akun' => 10,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-10',
                'waktu_transaksi' => '10:30:00',
                'jumlah_dibayar' => 50000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-09',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 11,
                'id_akun' => 11,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-11',
                'waktu_transaksi' => '11:45:00',
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 12,
                'id_akun' => 12,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-12',
                'waktu_transaksi' => '13:00:00',
                'jumlah_dibayar' => 500000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 13,
                'id_akun' => 13,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-13',
                'waktu_transaksi' => '14:15:00',
                'jumlah_dibayar' => 100000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 14,
                'id_akun' => 14,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '15:30:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 3,
                'tanggal_jatuh_tempo' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 15,
                'id_akun' => 15,
                'id_perorangan' => null,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '16:45:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 3,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 16,
                'id_akun' => null,
                'id_perorangan' => 16,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '11:20:00',
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 17,
                'id_akun' => null,
                'id_perorangan' => 17,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 18,
                'id_akun' => null,
                'id_perorangan' => 18,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 19,
                'id_akun' => null,
                'id_perorangan' => 19,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 20,
                'id_akun' => null,
                'id_perorangan' => 20,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 21,
                'id_akun' => null,
                'id_perorangan' => 21,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 150000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 22,
                'id_akun' => null,
                'id_perorangan' => 22,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 725000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 23,
                'id_akun' => null,
                'id_perorangan' => 23,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 200000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 24,
                'id_akun' => null,
                'id_perorangan' => 24,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 25,
                'id_akun' => null,
                'id_perorangan' => 25,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 50000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 26,
                'id_akun' => null,
                'id_perorangan' => 26,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 325000,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 27,
                'id_akun' => null,
                'id_perorangan' => 27,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 500000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 28,
                'id_akun' => null,
                'id_perorangan' => 28,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 0,
                'metode_pembayaran' => 'transfer',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 29,
                'id_akun' => null,
                'id_perorangan' => 29,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-15',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 250000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 1,
                'tanggal_jatuh_tempo' => '2025-06-14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_transaksi' => 30,
                'id_akun' => null,
                'id_perorangan' => 30,
                'id_perusahaan' => 1,
                'tanggal_transaksi' => '2025-05-14',
                'waktu_transaksi' => '10:00:00',
                'jumlah_dibayar' => 175000,
                'metode_pembayaran' => 'tunai',
                'id_status_transaksi' => 2,
                'tanggal_jatuh_tempo' => '2025-06-13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('transaksis')->insert($transaksis);
    }
}
